/*
Copyright 2022 The Knative Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
	v1alpha1 "knative.dev/eventing-blockchain/pkg/apis/sources/v1alpha1"
)

// FakeBlockchainSources implements BlockchainSourceInterface
type FakeBlockchainSources struct {
	Fake *FakeSourcesV1alpha1
	ns   string
}

var blockchainsourcesResource = schema.GroupVersionResource{Group: "sources.knative.dev", Version: "v1alpha1", Resource: "blockchainsources"}

var blockchainsourcesKind = schema.GroupVersionKind{Group: "sources.knative.dev", Version: "v1alpha1", Kind: "BlockchainSource"}

// Get takes name of the blockchainSource, and returns the corresponding blockchainSource object, and an error if there is any.
func (c *FakeBlockchainSources) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.BlockchainSource, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(blockchainsourcesResource, c.ns, name), &v1alpha1.BlockchainSource{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.BlockchainSource), err
}

// List takes label and field selectors, and returns the list of BlockchainSources that match those selectors.
func (c *FakeBlockchainSources) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.BlockchainSourceList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(blockchainsourcesResource, blockchainsourcesKind, c.ns, opts), &v1alpha1.BlockchainSourceList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.BlockchainSourceList{ListMeta: obj.(*v1alpha1.BlockchainSourceList).ListMeta}
	for _, item := range obj.(*v1alpha1.BlockchainSourceList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested blockchainSources.
func (c *FakeBlockchainSources) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(blockchainsourcesResource, c.ns, opts))

}

// Create takes the representation of a blockchainSource and creates it.  Returns the server's representation of the blockchainSource, and an error, if there is any.
func (c *FakeBlockchainSources) Create(ctx context.Context, blockchainSource *v1alpha1.BlockchainSource, opts v1.CreateOptions) (result *v1alpha1.BlockchainSource, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(blockchainsourcesResource, c.ns, blockchainSource), &v1alpha1.BlockchainSource{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.BlockchainSource), err
}

// Update takes the representation of a blockchainSource and updates it. Returns the server's representation of the blockchainSource, and an error, if there is any.
func (c *FakeBlockchainSources) Update(ctx context.Context, blockchainSource *v1alpha1.BlockchainSource, opts v1.UpdateOptions) (result *v1alpha1.BlockchainSource, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(blockchainsourcesResource, c.ns, blockchainSource), &v1alpha1.BlockchainSource{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.BlockchainSource), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeBlockchainSources) UpdateStatus(ctx context.Context, blockchainSource *v1alpha1.BlockchainSource, opts v1.UpdateOptions) (*v1alpha1.BlockchainSource, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(blockchainsourcesResource, "status", c.ns, blockchainSource), &v1alpha1.BlockchainSource{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.BlockchainSource), err
}

// Delete takes name of the blockchainSource and deletes it. Returns an error if one occurs.
func (c *FakeBlockchainSources) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(blockchainsourcesResource, c.ns, name, opts), &v1alpha1.BlockchainSource{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeBlockchainSources) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(blockchainsourcesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.BlockchainSourceList{})
	return err
}

// Patch applies the patch and returns the patched blockchainSource.
func (c *FakeBlockchainSources) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.BlockchainSource, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(blockchainsourcesResource, c.ns, name, pt, data, subresources...), &v1alpha1.BlockchainSource{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.BlockchainSource), err
}
