/*
Copyright 2022 The Knative Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
	v1alpha1 "knative.dev/eventing-blockchain/pkg/apis/sources/v1alpha1"
	scheme "knative.dev/eventing-blockchain/pkg/client/clientset/versioned/scheme"
)

// BlockchainSourcesGetter has a method to return a BlockchainSourceInterface.
// A group's client should implement this interface.
type BlockchainSourcesGetter interface {
	BlockchainSources(namespace string) BlockchainSourceInterface
}

// BlockchainSourceInterface has methods to work with BlockchainSource resources.
type BlockchainSourceInterface interface {
	Create(ctx context.Context, blockchainSource *v1alpha1.BlockchainSource, opts v1.CreateOptions) (*v1alpha1.BlockchainSource, error)
	Update(ctx context.Context, blockchainSource *v1alpha1.BlockchainSource, opts v1.UpdateOptions) (*v1alpha1.BlockchainSource, error)
	UpdateStatus(ctx context.Context, blockchainSource *v1alpha1.BlockchainSource, opts v1.UpdateOptions) (*v1alpha1.BlockchainSource, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.BlockchainSource, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.BlockchainSourceList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.BlockchainSource, err error)
	BlockchainSourceExpansion
}

// blockchainSources implements BlockchainSourceInterface
type blockchainSources struct {
	client rest.Interface
	ns     string
}

// newBlockchainSources returns a BlockchainSources
func newBlockchainSources(c *SourcesV1alpha1Client, namespace string) *blockchainSources {
	return &blockchainSources{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the blockchainSource, and returns the corresponding blockchainSource object, and an error if there is any.
func (c *blockchainSources) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.BlockchainSource, err error) {
	result = &v1alpha1.BlockchainSource{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("blockchainsources").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of BlockchainSources that match those selectors.
func (c *blockchainSources) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.BlockchainSourceList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.BlockchainSourceList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("blockchainsources").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested blockchainSources.
func (c *blockchainSources) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("blockchainsources").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a blockchainSource and creates it.  Returns the server's representation of the blockchainSource, and an error, if there is any.
func (c *blockchainSources) Create(ctx context.Context, blockchainSource *v1alpha1.BlockchainSource, opts v1.CreateOptions) (result *v1alpha1.BlockchainSource, err error) {
	result = &v1alpha1.BlockchainSource{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("blockchainsources").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(blockchainSource).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a blockchainSource and updates it. Returns the server's representation of the blockchainSource, and an error, if there is any.
func (c *blockchainSources) Update(ctx context.Context, blockchainSource *v1alpha1.BlockchainSource, opts v1.UpdateOptions) (result *v1alpha1.BlockchainSource, err error) {
	result = &v1alpha1.BlockchainSource{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("blockchainsources").
		Name(blockchainSource.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(blockchainSource).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *blockchainSources) UpdateStatus(ctx context.Context, blockchainSource *v1alpha1.BlockchainSource, opts v1.UpdateOptions) (result *v1alpha1.BlockchainSource, err error) {
	result = &v1alpha1.BlockchainSource{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("blockchainsources").
		Name(blockchainSource.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(blockchainSource).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the blockchainSource and deletes it. Returns an error if one occurs.
func (c *blockchainSources) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("blockchainsources").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *blockchainSources) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("blockchainsources").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched blockchainSource.
func (c *blockchainSources) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.BlockchainSource, err error) {
	result = &v1alpha1.BlockchainSource{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("blockchainsources").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
